version: "3.9"

services:

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - rails-postgres:/var/lib/postgresql/data

  rails:
    build:
      context: .
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    volumes:
      - ./sticker-donkey-api:/usr/src
    command: bundle exec rails s -b 0.0.0.0
    links:
      - postgres
    ports:
      - '3000:3000'
  
  react:
    build:
      dockerfile: Dockerfile.react
      context: .
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    volumes:
      - ./sticker-donkey-react:/app
    command: npm run dev
    ports:
      - '4000:4000'

volumes:
  rails-postgres: